# This is a basic workflow to compile the scss source files to css.

name: compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install sass
        run: npm install -g sass

      - name: Change file permission
        run: chmod +x ./build/compile.sh
      
      - name: Run the compilation script
        run: ./build/compile.sh

      - name: Print current working directory
        run: pwd
